package db;

import java.util.List;
import control.DataAccessException;
import model.Student;

public interface StudentDbIF {
	
	 /*// removed because we use autogenerated id
	  * Student create(Student student) throws DataAccessException;
	  */
	 
	 Student createWithIdentity(String name,boolean fullAssociation)  throws DataAccessException;
	 
	 Student update(Student student) throws DataAccessException;
	 
	 boolean delete(int id) throws DataAccessException;
	 
	 Student findById(int id, boolean fullAssociation) throws DataAccessException;
	 
	 //added because of the Teams
	 
	 List<Student> findByName(String name, boolean fullAssociation) throws DataAccessException;
	 
	 List<Student> getAll(boolean fullAssociation) throws DataAccessException;

	 List<Student> findByTeamId(int teamId, boolean fullAssociation) throws DataAccessException;


}
